name: Module Tests

on:
  pull_request:
    branches:
      - main
    paths:
      - "**.bicep"
      - "tests/pester/**.ps1"
  workflow_dispatch: {}

env:
  ARM_BILLING_SCOPE_RID: "${{ secrets.ARM_BILLING_SCOPE_RID }}"
  ARM_LOCATION: "uksouth"
  ARM_TENANT_ID: "${{ secrets.ARM_TENANT_ID }}"
  ARM_CLIENT_ID: "${{ secrets.ARM_CLIENT_ID }}"
  ARM_CLIENT_SECRET: "${{ secrets.ARM_CLIENT_SECRET }}"
  GH_PR_NUMBER: "${{ github.event.number }}"

jobs:
  vending:
    name: Vending Subscription for Tests and Networking Scenarios
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repo
        id: checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Azure Login
        id: login
        uses: azure/login@v1
        with:
          creds: '{"clientId":"${{ env.ARM_CLIENT_ID }}","clientSecret":"${{ env.ARM_CLIENT_SECRET }}","tenantId":"${{ env.ARM_TENANT_ID }}"}'
          enable-AzPSSession: true
          allow-no-subscriptions: true

      # - name: Vend Subscriptions & Networking Scenarios (What-If & Validate)
      #   id: vend-whatif
      #   uses: azure/powershell@v1
      #   with:
      #     inlineScript: |
      #       $inputObject = @{
      #         DeploymentName        = 'pr-${{ env.GH_PR_NUMBER }}-lz-vend-{0}' -f (-join (Get-Date -Format 'yyyyMMddTHHMMssffffZ')[0..63])
      #         ManagementGroupId     = "bicep-lz-vending-automation"
      #         Location              = "${{ env.ARM_LOCATION }}"
      #         TemplateFile          = "./tests/lz-vending/full.test.bicep"
      #         TemplateParameterObject =  @{
      #           location = "${{ env.ARM_LOCATION }}"
      #           prNumber = "${{ env.GH_PR_NUMBER }}"
      #           subscriptionBillingScope = "${{ env.ARM_BILLING_SCOPE_RID }}"
      #         }
      #       }
      #       New-AzManagementGroupDeployment @inputObject -Whatif
      #     azPSVersion: "latest"

      - name: Vend Subscriptions & Networking Scenarios (Deploy)
        id: vend
        uses: azure/powershell@v1
        with:
          inlineScript: |
            $inputObject = @{
              DeploymentName        = 'pr-${{ env.GH_PR_NUMBER }}-lz-vend-{0}' -f (-join (Get-Date -Format 'yyyyMMddTHHMMssffffZ')[0..63])
              ManagementGroupId     = "bicep-lz-vending-automation"
              Location              = "${{ env.ARM_LOCATION }}"
              TemplateFile          = "./tests/lz-vending/full.test.bicep"
              TemplateParameterObject =  @{
                location = "${{ env.ARM_LOCATION }}"
                prNumber = "${{ env.GH_PR_NUMBER }}"
                subscriptionBillingScope = "${{ env.ARM_BILLING_SCOPE_RID }}"
              }
            }
            $bicepDeployment = New-AzManagementGroupDeployment @inputObject
            $outputValue = $bicepDeployment.properties.outputs.createdSubId.value
            echo "SUBID=$outputValue" >> $GITHUB_ENV
          azPSVersion: "latest"

      - name: Var Console Output
        id: var
        run: |
          write-host "SUBID 1: ${{ env.SUBID }}"
          write-host "SUBID 2:" ${{ env:SUBID }}
          write-host "SUBID 3: $env:SUBID"
          write-host "SUBID 4: ${{ steps.vend.outputs.SUBID }}"
        shell: pwsh

      - name: Pester Tests
        id: pester
        uses: azure/powershell@v1
        with:
          inlineScript: |
            Import-Module Pester -Force
            $configuration = [PesterConfiguration]::Default
            $configuration.TestResult.Enabled = $true
            $configuration.Output.Verbosity = 'Detailed'
            $container = New-PesterContainer -Path "./tests/pester/*.tests.ps1" -Data @{ subId = "${{ env.SUBID }}"; prNumber = "${{ env.GH_PR_NUMBER }}"; location = "${{ env.ARM_LOCATION }}" }
            $configuration.Run.Container = $container
            $configuration.Run.PassThru = $true
            Invoke-Pester -Configuration $configuration
          azPSVersion: "latest"
