name: Release Tests

on:
  pull_request:
    branches:
      - main
  workflow_dispatch: {}

jobs:
  vending:
    name: Vending Subscription for Tests and Networking Scenarios
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repo
        id: checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Pester Tests
        id: pester
        if: contains(github.ref, 'release')
        uses: azure/powershell@v1
        with:
          inlineScript: |
            Import-Module Pester -Force
            $pesterConfiguration = @{
              Run    = @{
                Container = New-PesterContainer -Path "./tests/pester/release.tests.ps1"
                PassThru  = $true
              }
              Output = @{
                Verbosity = 'Detailed'
              }
            }
            $result = Invoke-Pester -Configuration $pesterConfiguration
            exit $result.FailedCount
          azPSVersion: "latest"


